Feature/basst314/space client configuration
basst314/space pull request #7
Opened 2016-12-10 19:43 UTC by basst314

Hi,
hab das Angular2 Setup soweit abgeschlossen. Wird beim Build über Travis auch mit gebuildet. Ergebnis ist dzt., dass die gebuildete Angular2-App im FatJar vom Space-Server (Space-Server-*-all.jar) integriert wird, so dass sie beim Deployment auf Heroku direkt aufrufbar sein müsste.

Im Space-Client sind auch schon Unit- und Integrationtests enthalten. Als Loader wird Webpack verwendet.
Ausgangslage war dieser [Seed](https://github.com/AngularClass/angular2-webpack-starter).

Lg,
Basti

2016-12-10 19:48 UTC, basst314 commented
zur Info wg Ausprobieren: hab a kurze [Doku](https://github.com/basst314/space/tree/feature/basst314/space-client-configuration/space-client#space-client) dazu geschrieben.

2016-12-13 12:20 UTC, oppes requested changes
also features werden ja grundsätzlich mal in master gemerged.
und wenn der master eben a stabile version is kann ma drüber reden ob der master in stable branch übernommen wird :)

2016-12-13 12:22 UTC, oppes commented
grad jetz beim ausprobiern vo dem angular zeugs kannst ja eigentlihc heroku einfach umstelln und auf deinen branch zeigen lassen? weils ja eh noch in der anfangsphase vom projekt is

2016-12-13 13:06 UTC, basst314 commented
ok, dachte anders rum :+1:

2016-12-13 13:06 UTC, closed without merging